name: 'Build/Deploy'
description: 'Deploy'
inputs:
  enviroment:
    required: true
  port:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        repository: 'mtararujs/python-greetings'
        path: 'depl'
    - name: Delete
      working-directory: ./depl
      run: pm2 delete greetings-app-${{ inputs.enviroment }}  & set "errorlevel=0"
      shell: pwsh
    - name: Start
      working-directory: ./depl
      run: pm2 start app.py --name greetings-app-${{ inputs.enviroment }} --interpreter ../deps/venv/bin/python.exe
      #-- -- ${{ inputs.port }}
      shell: pwsh
