name: 'Build/Deploy'
description: 'Deploy'
inputs:
  enviroment:
    required: true
  port:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        repository: 'mtararujs/python-greetings'
        path: 'deps'
    - name: Delete
      working-directory: ./deps
      run: pm2 delete greetings-app-${{ inputs.enviroment }}; exit 0
      shell: pwsh
    - name: Start
      working-directory: ./deps
      run: pm2 start -n greetings-app-${{ inputs.enviroment }} .venv\bin\python app.py -- -- ${{ inputs.port }}
      shell: pwsh
