name: 'Build/Deploy'
description: 'Deploy'
inputs:
  enviroment:
    required: true
  port:
    required: true
runs: 
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        repository: 'mtararujs/python-greetings'
        clean: 'false'
        path: 'depl'
        
    - name: Delete process if there was one
      working-directory: ./depl
      run: pm2 delete greetings-app-${{ inputs.enviroment }} || true
      shell: bash
    
    - name: Start
      working-directory: ./depl
      run:  pm2 start app.py --name greetings-app-${{ inputs.enviroment }} --interpreter $GITHUB_WORKSPACE/deps/venv/bin/python -- --port ${{inputs.port}}
      shell: bash
