# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          clean: 'false'
      - uses: ./.github/Actions/Build
      

        
  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: actions/checkout@v6
        with:
          clean: 'false'
      - uses: ./.github/Actions/Deploy
        with:
          enviroment: 'dev'
          port: '7001'
      - name: Deploy
        run: echo "to dev"
        
  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - uses: actions/checkout@v6
        with:
          clean: 'false'
      - uses: ./.github/Actions/Test
        with:
          enviroment: 'dev'
      - name: Run a one-line script
        run: echo "test dev"
  deploy-to-stg:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - uses: actions/checkout@v6
        with:
          clean: 'false'
      - uses: ./.github/Actions/Deploy
        with:
          enviroment: 'stg'
          port: '7002'
      - name: Deploy
        run: echo "to stg"
  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps:
      - uses: actions/checkout@v6
        with:
          clean: 'false'
      - uses: ./.github/Actions/Test
        with:
          enviroment: 'stg'
      - name: Run a one-line script
        run: echo "test stg"
  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - uses: actions/checkout@v6
        with:
          clean: 'false'
      - uses: ./.github/Actions/Deploy
        with:
          enviroment: 'preprod'
          port: '7003'
      - name: Deploy
        run: echo "to pre"
  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - uses: actions/checkout@v6
        with:
          clean: 'false'
      - uses: ./.github/Actions/Test
        with:
          enviroment: 'preprod'
      - uses: actions/checkout@v6
      - name: Run a one-line script
        run: echo "test pre"
  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - uses: actions/checkout@v6
        with:
          clean: 'false'
      - uses: ./.github/Actions/Deploy
        with:
          enviroment: 'prod'
          port: '7004'
      - name: Run a one-line script
        run: echo "to prod"
  Tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - uses: actions/checkout@v6
        with:
          clean: 'false'
      - uses: ./.github/Actions/Test
        with:
          enviroment: 'prod'
      - name: Run a one-line script
        run: echo "test prod"
 


    
