# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  install-pip-deps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/Actions/Build

        
  deploy-to-dev:
    runs-on: windows-latest
    needs: install-pip-deps
    steps:
    
      - uses: actions/checkout@v6
      - name: Run a one-line script
        run: echo "to dev"
  tests-on-dev:
    runs-on: windows-latest
    needs: deploy-to-dev
    steps:
    
      - uses: actions/checkout@v6
      - name: Run a one-line script
        run: echo "test dev"
  deploy-to-stg:
    runs-on: windows-latest
    needs: tests-on-dev
    steps:
      
      - uses: actions/checkout@v6
      - name: Run a one-line script
        run: echo "to stg"
  tests-on-stg:
    runs-on: windows-latest
    needs: deploy-to-stg
    steps:
    
      - uses: actions/checkout@v6
      - name: Run a one-line script
        run: echo "test stg"
  deploy-to-preprod:
    runs-on: windows-latest
    needs: tests-on-stg
    steps:
    
      - uses: actions/checkout@v6
      - name: Run a one-line script
        run: echo "to pre"
  tests-on-preprod:
    runs-on: windows-latest
    needs: deploy-to-preprod
    steps:
    
      - uses: actions/checkout@v6
      - name: Run a one-line script
        run: echo "test pre"
  deploy-to-prod:
    runs-on: windows-latest
    needs: tests-on-preprod
    steps:
    
      - uses: actions/checkout@v6
      - name: Run a one-line script
        run: echo "to prod"
  Tests-on-prod:
    runs-on: windows-latest
    needs: deploy-to-prod
    steps:
    
      - uses: actions/checkout@v6
      - name: Run a one-line script
        run: echo "test prod"

  


    
